# Generated by Django 3.2.16 on 2023-12-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='event_redirecturl',
            field=models.CharField(max_length=255),
        ),
    ]
