# Generated by Django 3.2.16 on 2023-12-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_wishlist_event_redirecturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='event_title',
            field=models.CharField(max_length=255),
        ),
    ]
