# Generated by Django 3.2.16 on 2023-12-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_wishlist_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='event_image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='event_redirecturl',
            field=models.CharField(max_length=300),
        ),
    ]
