# Generated by Django 3.2.16 on 2023-12-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20231211_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic/'),
        ),
    ]
