# Generated by Django 3.2.16 on 2023-12-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_reviews'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='reviews',
            order_with_respect_to='user',
        ),
    ]
