# Generated by Django 3.2.16 on 2023-12-22 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('event_redirecturl', models.CharField(max_length=300)),
                ('event_price', models.CharField(max_length=255)),
                ('event_image', models.CharField(max_length=500)),
                ('number_of_adults', models.PositiveIntegerField()),
                ('date_of_booking', models.DateTimeField(auto_now=True)),
                ('check_in_date', models.DateField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
